name: WaterdogLobbyFallback
main: com.arvangaming.wdlf.WaterdogLobbyFallback
version: 1.0.0
author: ArvanGaming
description: Sends players to a configured WaterdogPE lobby when a backend server goes offline.
